language: node_js
node_js:
- '4'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
before_install:
- export CC="gcc-4.9" CXX="g++-4.9"
deploy:
  provider: npm
  email: seb.cottinet@gmail.com
  api_key:
    secure: p41aWRluh35f2KlpSiuS+AJAQdGRMcOXqooMAmfnu6LRtlNxpndjuK4xOm5WOmZNMg6MWFTKIEmxje2rFUT+k2coQkclVocW5WvdQqAwCjUi8smyIoXPU2NPnbAtacnQ2U0u8keU9FO1/kg2oofELSOrkDkUuxPDEg75Br2ZaC2vOiew2dj2/r5dRBGTJzSzjHBVlYdVLCQh5dxpaEfk33X3aSOknS6tZZ13wOD9r/+mJXFgH2y0baDWDLukQyI1ldtv7Dl7Sc2CdPJQ+AO3JKFfD1gfy4HZFwYY+37gDv/3ErmrEPaQ7oB9ALCYoGOfHCaDwmYf+B9RFU9QIKu+1kZUA9+EKgMc1ScTzKkgnP7nifsoQ1gUF3Nuz05SiIbQW0ZSLTgq1OXHL+oAjMrb3b0vMr63uZnouXWlDVgnkgfc6dmCWTl/Zv2oxREuiWsFJxCHZlid7F8NBgyi5bRbJTKy9pLoBftsyn0QWt2iuhhC6ldDbZZc8fpQAMf1Ybgpke1zAAhicWMdXOmKrpGq/J963CRXA96nCEPIq8as91/fU53vtJaj+MKH0ZHeMfvz/AmLTglU7Ae7p9vyJZhaefGJaZGXRZMoOBrF53i3ZPqWTUJ4nQDn+y+6FKIudo6oG8jz40dCL9VZut9VGL0B2NZXbLodFpIQwlXzBBaTr4g=
  on:
    repo: scottinet/espresso-logic-minimizer
    branch: master
